### PR TITLE
Put real sceNpDrmPackage functions names

### PR DESCRIPTION
**Pull request by devnoname120**
Found the names corresponding to these NIDs on the Internet.

### CODE REVIEW

**Comment by 173210** [comment]
> on the Internet

LOL
I'll review tomorrow (It's 22:30 JST).

**Comment by 173210** [comment]
I googled and found this:
http://pastebin.com/iGFQ9jfe

Looks like legitimate, but it says:

> _sceNpDrmPackageDecrypt
> 
> _sceNpDrmPackageCheck

Adding prefix `_` makes sense since those functions seems used in a userland library named `sceNpDrmPackage` and it's likely to show they are internal functions for the library. I'll change the names with the prefix.

**Comment by devnoname120** [comment]
Right, this is where I found them.

I was unsure about the `_` prefix since some functions seem to be defined with and without _. (e.g. `_sceKernelCreateSema` and `sceKernelCreateSema` which don't have the same NID.)

**Comment by 173210** [comment]
Pushed 2acf5810b1b180a355fa146acbd844fe562e074c.

**Comment by devnoname120** [comment]
Thank you for your clarifications.

**Pull request closed without merging**
